# Generated by Django 2.2.6 on 2019-11-07 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20191030_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 18, 55, 56, 706877, tzinfo=utc), verbose_name='date deployed'),
        ),
    ]
