# Generated by Django 2.2.6 on 2019-11-30 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0006_auto_20191107_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='flow_duration',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='pump_wait',
        ),
        migrations.AddField(
            model_name='deployment',
            name='depth_band',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='min_flow_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='temp_band',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ticks_per_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='wait_pump_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployment',
            name='wait_pump_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 21, 44, 9, 822861, tzinfo=utc), verbose_name='date deployed'),
        ),
    ]
