# Generated by Django 2.2.6 on 2019-12-02 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0009_auto_20191201_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 2, 16, 996359, tzinfo=utc), verbose_name='date deployed'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='temperature',
            field=models.FloatField(default=-273.15),
        ),
    ]
