# Generated by Django 2.2.6 on 2019-12-07 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0010_auto_20191202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='notes',
            field=models.TextField(default='Please insert deployment note here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 2, 54, 7, 790605, tzinfo=utc), verbose_name='date deployed'),
        ),
    ]
